name: Test Frontend on pr

on: [pull_request,pull_request_review]

env:
  FRONTEND_DIRECTORY: "./cookowly-frontend"

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
        working-directory: "$FRONTEND_DIRECTORY"
      - name: Install playwright browsers
        run: npx playwright install --with-deps
        working-directory: "$FRONTEND_DIRECTORY"
      - name: Run tests
        run: npx playwright test
        working-directory: "$FRONTEND_DIRECTORY"